name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - run: pip install pre-commit
      # - run: pre-commit run --all-files
      
      - uses: actions/setup-node@v4

      - run: npm ci
      - run: npx prettier --write .

      - uses: autofix-ci/action@v1.0.0
