name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - run: pip install pre-commit
      # - run: pre-commit run --all-files
      
      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: package-lock.json
          
      - run: npm ci
      - run: npx prettier --write .
      # or, if you are using yarn:
      # - run: yarn
      # - run: yarn prettier --write .

      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
